name: Deploy Frontend to ConoHa VPS Staging Server

on:
  push:
    branches:
      - develop

jobs:
  deploy_to_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key for Deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.TENNISLOG_SSH_PRIVATE_KEY }}
          host: ${{ secrets.STAGING_HOST_IP }}
          username: ${{ secrets.STAGING_SSH_USER }}
          port: ${{ secrets.STAGING_SSH_PORT }}
          script: |
            cd ./tennis_log_front
            git pull origin develop
            npm ci
            npm run build
            pm2 restart tennis-log
